name: Discussion Notifier

on:
  discussion:
    types: [created]

jobs:
  discussion:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: Get Info
          run: |
            df -h
